/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stm32g4xx_ll_gpio.c"
#include "SystemClock.h"

#define LED_Pin LL_GPIO_PIN_5
#define LED_GPIO_Port GPIOA

#define BUT_Pin LL_GPIO_PIN_13
#define BUT_GPIO_Port GPIOC

uint32_t button_status;
uint32_t LED_status;

int main(void)
{
	SystemClockInit();

	LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_SYSCFG);
	LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_PWR);

	LL_GPIO_InitTypeDef GPIO_InitStruct = {0};

	LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOA);
	LL_GPIO_ResetOutputPin(LED_GPIO_Port, LED_Pin);

	GPIO_InitStruct.Pin = LED_Pin;
	GPIO_InitStruct.Mode = LL_GPIO_MODE_OUTPUT;
	GPIO_InitStruct.Speed = LL_GPIO_SPEED_FREQ_VERY_HIGH;
	GPIO_InitStruct.OutputType = LL_GPIO_OUTPUT_PUSHPULL;
	GPIO_InitStruct.Pull = LL_GPIO_PULL_NO;
	LL_GPIO_Init(LED_GPIO_Port, &GPIO_InitStruct);


	LL_AHB2_GRP1_EnableClock(LL_AHB2_GRP1_PERIPH_GPIOC);
	LL_GPIO_ResetOutputPin(BUT_GPIO_Port, BUT_Pin);

	GPIO_InitStruct.Pin = BUT_Pin;
	GPIO_InitStruct.Mode = LL_GPIO_MODE_INPUT;
	GPIO_InitStruct.Pull = LL_GPIO_PULL_NO;
	LL_GPIO_Init(BUT_GPIO_Port, &GPIO_InitStruct);

	while(1)
	{
		if(LL_GPIO_ReadInputPort(GPIOC) & LL_GPIO_PIN_13){
			LED_status = LL_GPIO_PIN_5;
			LL_GPIO_SetOutputPin(LED_GPIO_Port, LED_Pin);
		}
		else{
			LL_GPIO_ResetOutputPin(LED_GPIO_Port, LED_Pin);
		}
	}
}
//
